### ISSUE TITLE
Check for class 'form-group' is nice but is done too early.

### ISSUE THREAD

**Issue by lucasmaj** [paulyoder/angular-bootstrap-show-errors#15]
Thanks for this great directive. Really really thank you!

IMHO Check for class 'form-group' is nice but is done too early. It is a nice trick to do it during compilation phase but in my case 'form-group' class is added later by another directive during that directive's postLink function. 

To fix my issue I moved the check to beginning of linkFn.

Any feedback is appreciated.

Thanks again!

**Comment by paulyoder** [comment]
version 2.2.0 now has the option to skip the 'form-group' class.

    <div show-errors="{ skipFormGroupCheck: true }">

I'm going to close this issue, but feel free to re-open it if this solution doesn't work for you.
