### ISSUE TITLE
Radio Boxes

### ISSUE THREAD

**Issue by D-Bullock** [paulyoder/angular-bootstrap-show-errors#20]
Hey,

I love what you have done, but I seem to have hit a problem that hasn't been accounted for, 

I have the following code:
```
<label class="radio-inline">
	<input type="radio" name="gender" ng-model="model.gender" required value="Male" />Male
</label>
<label class="radio-inline">
	<input type="radio" name="gender" ng-model="model.gender" required value="Female" />Female
</label>
```
For a button group, there isn't meant to be any form-control class on the inputs. 
Is there any way of using your plugin to show errors here?

**Comment by paulyoder** [comment]
version 2.2.0 now has support for radio boxes. I'll close this issue, but feel free to re-open it if you run into any issues.

**Comment by chrisfosterelli** [comment]
Did the revert in version 2.3.0 break radio button support @paulyoder?
