### ISSUE TITLE
Consider publishing on npm

### ISSUE THREAD

**Issue by chrisfosterelli** [paulyoder/angular-bootstrap-show-errors#27]
Hey, I noticed it looks like you have a `package.json` file for this repository, but the actual package (`angular-bootstrap-show-errors`) does not exist in npm.

I'm using the bower version for now, but I've been trying to use npm versions of packages where possible. It's worth considering publishing this to npm!

Thanks for the hard work on this package btw!

**Comment by paulyoder** [comment]
I just published version 2.2.0 on npm. Thanks!

**Comment by chrisfosterelli** [comment]
Awesome, thanks @paulyoder!
