### ISSUE TITLE
show-errors no longer works with dropdown selects

### ISSUE THREAD

**Issue by sdgidwani** [paulyoder/angular-bootstrap-show-errors#33]
With the change of the element queryselector to select elements based on type input and not an applied class of .form-control we have lost the ability to use show-errors to validate dropdown select boxes.

**Comment by xiphiaz** [comment]
+1 This occurred at the change https://github.com/paulyoder/angular-bootstrap-show-errors/commit/e93c512acc619c179d191ae6692a17c6bcef50c5

**Comment by paulyoder** [comment]
Sorry about this breaking change. I reverted the commit that caused the breaking change and published v2.3.0 to fix it.
